feat: add command line to convert files
openapi-contrib/json-schema-to-openapi-schema pull request #24
Opened 2021-07-25 14:29 UTC by diegotremper

This PR introduces a command-line option to this package.

Thanks!

2021-07-28 07:55 UTC, stephenlprice requested changes
Reviewed the CLI functionality by installing the repo and then ran the following tests:

- [x] `npm test` 45 passing (all)
- [x] check that help messages work properly for the package and the convert command
- [x] tested the convert command in REPL using the basic example described in the README
```js
const schema = {
   '$schema': 'http://json-schema.org/draft-04/schema#',
   type: ['string', 'null'],
   format: 'date-time',

const convert = require('@openapi-contrib/json-schema-to-openapi-schema');

(async () => {
   const convertedSchema = await convert(schema);
   console.log(convertedSchema);
})();

// returned
{ type: 'string', format: 'date-time', nullable: true }
};
```
- [x] converted the "basic" and "address" examples and verified they match the OpenAPI provided for each by using:
```bash
npx json-schema-to-openapi-schema convert address/json-schema.json > address/address-oas.json
```

Everything looks good to me, I would just correct the one typo described in the comment and approve

2021-07-29 03:53 UTC, diegotremper commented on bin/help-text.json
> +    "Returns a non-zero exit code if convertion fails.",
Good catch! I fixed this issue and amend the latest commit. Thanks!

2021-07-29 07:56 UTC, philsturgeon approved these changes

2021-07-29 07:56 UTC, merged

2021-07-29 07:59 UTC, philsturgeon commented
Done! Thank you for this amazing work.

Hopefully you won’t need it for long and can get up to OpenAPI v3.1 instead of having to convert stuff, but until everyone is upgraded many people will be grateful for this.

On Thu, Jul 29, 2021 at 09:57, github-actions[bot] ***@***.***> wrote:

> 🎉 This PR is included in version 2.1.0 🎉
>
> The release is available on:
>
> - [npm package ***@***.*** ***@***.***/json-schema-to-openapi-schema/v/2.1.0)
> - [GitHub release](https://github.com/openapi-contrib/json-schema-to-openapi-schema/releases/tag/v2.1.0)
>
> Your [semantic-release](https://github.com/semantic-release/semantic-release) bot 📦🚀
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, [view it on GitHub](https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/24#issuecomment-888890192), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAAQONNVTCVMPUGTUGCI6MTT2ECYBANCNFSM5A6S77KA).